// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaterCalculator.Database;

#nullable disable

namespace WaterCalculator.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260623162350_add_statuses")]
    partial class add_statuses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("WaterCalculator.Domain.Apartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("apartment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("apartment_created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("apartment_details");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("apartment_name");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("Name");

                    b.ToTable("apartments", (string)null);
                });

            modelBuilder.Entity("WaterCalculator.Domain.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("group_details");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("group_name");

                    b.HasKey("Id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("WaterCalculator.Domain.Invoices.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_number");

                    b.Property<DateTime>("PeriodFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_period_from");

                    b.Property<DateTime>("PeriodTo")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_period_to");

                    b.Property<DateTime>("SettledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_settled_at");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("invoice_status");

                    b.Property<decimal>("TotalConsumption")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_total_consumption");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_total_price");

                    b.HasKey("Id");

                    b.HasIndex("PeriodFrom");

                    b.HasIndex("PeriodTo");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("WaterCalculator.Domain.Invoices.InvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ii_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT")
                        .HasColumnName("ii_amount");

                    b.Property<int>("CalculationType")
                        .HasColumnType("ii_calculation_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ii_created_at");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ii_invoice_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("ii_name");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("TEXT")
                        .HasColumnName("ii_price_per_unit");

                    b.Property<decimal>("TotalBruttoPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("ii_total_brutto_price");

                    b.Property<decimal>("TotalNettoPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("ii_total_netto_price");

                    b.Property<int>("Vat")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ii_vat");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_items", (string)null);
                });

            modelBuilder.Entity("WaterCalculator.Domain.Reads.Read", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("read_id");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("apartment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReadDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("read_date");

                    b.Property<DateTime>("SettledAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("read_settled_at");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("read_status");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("reads", (string)null);
                });

            modelBuilder.Entity("WaterCalculator.Domain.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("settlement_id");

                    b.Property<decimal>("AmountToPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount_to_pay");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("apartment_id");

                    b.Property<decimal>("Consumption")
                        .HasColumnType("TEXT")
                        .HasColumnName("consumption");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_id");

                    b.Property<int>("RealizationStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realization_status");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("InvoiceId");

                    b.ToTable("settlements", (string)null);
                });

            modelBuilder.Entity("WaterCalculator.Domain.Apartment", b =>
                {
                    b.HasOne("WaterCalculator.Domain.Group", "Group")
                        .WithMany("Apartments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("WaterCalculator.Domain.Invoices.InvoiceItem", b =>
                {
                    b.HasOne("WaterCalculator.Domain.Invoices.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("WaterCalculator.Domain.Reads.Read", b =>
                {
                    b.HasOne("WaterCalculator.Domain.Apartment", "Apartment")
                        .WithMany("Reads")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("WaterCalculator.Domain.Settlement", b =>
                {
                    b.HasOne("WaterCalculator.Domain.Apartment", "Apartment")
                        .WithMany("Settlements")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterCalculator.Domain.Invoices.Invoice", "Invoice")
                        .WithMany("Settlements")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("WaterCalculator.Domain.Apartment", b =>
                {
                    b.Navigation("Reads");

                    b.Navigation("Settlements");
                });

            modelBuilder.Entity("WaterCalculator.Domain.Group", b =>
                {
                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("WaterCalculator.Domain.Invoices.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");

                    b.Navigation("Settlements");
                });
#pragma warning restore 612, 618
        }
    }
}
