// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaterCalculator.Database;

#nullable disable

namespace WaterCalculator.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("WaterCalculator.Domain.Apartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("apartment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("apartment_created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("apartment_details");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("apartment_name");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("Name");

                    b.ToTable("apartments", (string)null);
                });

            modelBuilder.Entity("WaterCalculator.Domain.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("group_details");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("group_name");

                    b.HasKey("Id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("WaterCalculator.Domain.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_number");

                    b.Property<DateTime>("PeriodFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_period_from");

                    b.Property<DateTime>("PeriodTo")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_period_to");

                    b.Property<decimal>("TotalConsumption")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_total_consumption");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_total_price");

                    b.HasKey("Id");

                    b.HasIndex("PeriodFrom");

                    b.HasIndex("PeriodTo");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("WaterCalculator.Domain.Read", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("read_id");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL")
                        .HasColumnName("amount");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("reads", (string)null);
                });

            modelBuilder.Entity("WaterCalculator.Domain.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("settlement_id");

                    b.Property<decimal>("AmountToPay")
                        .HasColumnType("TEXT")
                        .HasColumnName("amount_to_pay");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("apartment_id");

                    b.Property<decimal>("Consumption")
                        .HasColumnType("TEXT")
                        .HasColumnName("consumption");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_id");

                    b.Property<int>("RealizationStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realization_status");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("InvoiceId");

                    b.ToTable("settlements", (string)null);
                });

            modelBuilder.Entity("WaterCalculator.Domain.Apartment", b =>
                {
                    b.HasOne("WaterCalculator.Domain.Group", "Group")
                        .WithMany("Apartments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("WaterCalculator.Domain.Read", b =>
                {
                    b.HasOne("WaterCalculator.Domain.Apartment", "Apartment")
                        .WithMany("Reads")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("WaterCalculator.Domain.Settlement", b =>
                {
                    b.HasOne("WaterCalculator.Domain.Apartment", "Apartment")
                        .WithMany("Settlements")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WaterCalculator.Domain.Invoice", "Invoice")
                        .WithMany("Settlements")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("WaterCalculator.Domain.Apartment", b =>
                {
                    b.Navigation("Reads");

                    b.Navigation("Settlements");
                });

            modelBuilder.Entity("WaterCalculator.Domain.Group", b =>
                {
                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("WaterCalculator.Domain.Invoice", b =>
                {
                    b.Navigation("Settlements");
                });
#pragma warning restore 612, 618
        }
    }
}
